package main

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	textExtensionFileNumber     = 50001
	labelExtensionFileNumber    = 50002
	comboExtensionFileNumber    = 50003
	comboDefExtensionFileNumber = 50004
)

type ComboDef struct {
	MethodName  string
	Description string
}

func main() {
	var targetDir string

	opts := protogen.Options{
		ParamFunc: func(key, value string) error {
			if key == "target_dir" {
				targetDir = value
			}
			return nil
		},
	}

	opts.Run(func(gen *protogen.Plugin) error {
		if targetDir == "" && gen.Request.Parameter != nil {
			for _, param := range strings.Split(gen.Request.GetParameter(), ",") {
				parts := strings.SplitN(param, "=", 2)
				if len(parts) == 2 && strings.TrimSpace(parts[0]) == "target_dir" {
					targetDir = strings.TrimSpace(parts[1])
					break
				}
			}
		}

		if targetDir != "" {
			targetDir = strings.ReplaceAll(targetDir, "\\", "/")
			if !strings.HasSuffix(targetDir, "/") {
				targetDir += "/"
			}
		}

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}

			filePath := strings.ReplaceAll(f.Desc.Path(), "\\", "/")
			if targetDir != "" && !strings.HasPrefix(filePath, targetDir) {
				continue
			}

			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	if len(file.Enums) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + ".pb.enum.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go-enum. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	hasUint8Mode := false

	type resolvedEnum struct {
		enum         *protogen.Enum
		isStringMode bool
	}
	var list []resolvedEnum

	for _, enum := range file.Enums {
		isStringMode := false
		for _, v := range enum.Values {
			extMap := parseEnumValueExtensions(v.Desc.Options().(*descriptorpb.EnumValueOptions))
			if len(extMap[labelExtensionFileNumber]) > 0 {
				isStringMode = true
				break
			}
		}
		if !isStringMode {
			hasUint8Mode = true
		}
		list = append(list, resolvedEnum{enum: enum, isStringMode: isStringMode})
	}

	g.P("import (")
	g.P(`	"database/sql/driver"`)
	g.P(`	"encoding/json"`)
	g.P(`	"fmt"`)
	if hasUint8Mode {
		g.P(`	"strconv"`)
	}
	if hasUint8Mode {
		g.P(`	"strings"`)
	}
	g.P(")")
	g.P()

	for _, item := range list {
		genEnumMethods(g, item.enum, item.isStringMode)
	}
}

func genEnumMethods(g *protogen.GeneratedFile, enum *protogen.Enum, isStringMode bool) {
	enumName := enum.GoIdent.GoName
	textMapName := lowercaseFirst(enumName) + "TextMap"

	type enumOpts struct {
		text  string
		label string
	}
	optsResolved := make(map[string]enumOpts)

	for _, v := range enum.Values {
		nameStr := string(v.Desc.Name())
		extMap := parseEnumValueExtensions(v.Desc.Options().(*descriptorpb.EnumValueOptions))

		var lVal, tVal string
		if vals, ok := extMap[labelExtensionFileNumber]; ok && len(vals) > 0 {
			lVal = vals[0]
		}
		hasL := lVal != ""
		if !hasL {
			lVal = nameStr
		}

		if vals, ok := extMap[textExtensionFileNumber]; ok && len(vals) > 0 {
			tVal = vals[0]
		}
		if tVal == "" {
			if hasL {
				if vals, ok := extMap[labelExtensionFileNumber]; ok && len(vals) > 0 {
					tVal = vals[0]
				}
			} else {
				tVal = nameStr
			}
		}

		optsResolved[nameStr] = enumOpts{text: tVal, label: lVal}
	}

	if isStringMode {
		g.P("type ", enumName, " string")
	} else {
		g.P("type ", enumName, " uint8")
	}
	g.P()

	g.P("const (")
	for _, v := range enum.Values {
		nameStr := string(v.Desc.Name())
		cleanConstantName := getCleanConstantName(enumName, nameStr)

		if isStringMode {
			g.P("	", cleanConstantName, " ", enumName, ` = "`, optsResolved[nameStr].label, `"`)
		} else {
			// if i == 0 {
			// 	g.P("	", cleanConstantName, " ", enumName, " = iota")
			// } else {
			// 	g.P("	", cleanConstantName)
			// }
			g.P("	", cleanConstantName, " ", enumName, " = ", v.Desc.Number())
		}
	}
	g.P(")")
	g.P()

	g.P("var ", textMapName, " = map[", enumName, "]string{")
	for _, v := range enum.Values {
		nameStr := string(v.Desc.Name())
		cleanConstantName := getCleanConstantName(enumName, nameStr)
		g.P("	", cleanConstantName, `: "`, optsResolved[nameStr].text, `",`)
	}
	g.P("}")
	g.P()

	if isStringMode {
		g.P("func (s ", enumName, ") GetValue() string {")
		g.P("	return string(s)")
		g.P("}")
	} else {
		g.P("func (s ", enumName, ") GetValue() uint8 {")
		g.P("	return uint8(s)")
		g.P("}")
	}
	g.P()

	g.P("func (s ", enumName, ") GetText() string {")
	g.P("	tex, ok := ", textMapName, "[s]")
	g.P("	if !ok {")
	g.P("	   return \"\"")
	g.P("	}")
	g.P("	return tex")
	g.P("}")
	g.P()

	for _, v := range enum.Values {
		nameStr := string(v.Desc.Name())
		suffix := strings.TrimPrefix(nameStr, camelToSnake(enumName)+"_")
		methodName := "Is" + snakeToCamel(suffix)
		cleanConstantName := getCleanConstantName(enumName, nameStr)

		g.P("func (s ", enumName, ") ", methodName, "() bool {")
		g.P("	return s == ", cleanConstantName)
		g.P("}")
		g.P()
	}

	genComboMethods(g, enum)

	g.P("func (s ", enumName, ") Value() (driver.Value, error) {")
	if isStringMode {
		g.P("	return string(s), nil")
	} else {
		g.P("	return int64(s), nil")
	}
	g.P("}")
	g.P()

	g.P("func (s *", enumName, ") Scan(value interface{}) error {")
	g.P("	if value == nil {")
	if isStringMode {
		firstValueName := string(enum.Values[0].Desc.Name())
		g.P("	   *s = \"", optsResolved[firstValueName].label, "\"")
	} else {
		g.P("	   *s = 0")
	}
	g.P("	   return nil")
	g.P("	}")
	g.P()
	g.P("	switch v := value.(type) {")

	if isStringMode {
		g.P("	case string:")
		g.P("	   *s = ", enumName, "(v)")
		g.P("	case []byte:")
		g.P("	   *s = ", enumName, "(string(v))")
	} else {
		g.P("	case int64:")
		g.P("	   *s = ", enumName, "(v)")
		g.P("	case int32:")
		g.P("	   *s = ", enumName, "(v)")
		g.P("	case int16:")
		g.P("	   *s = ", enumName, "(v)")
		g.P("	case int8:")
		g.P("	   *s = ", enumName, "(v)")
		g.P("	case int:")
		g.P("	   *s = ", enumName, "(v)")
		g.P("	case uint64:")
		g.P("	   *s = ", enumName, "(v)")
		g.P("	case uint32:")
		g.P("	   *s = ", enumName, "(v)")
		g.P("	case uint16:")
		g.P("	   *s = ", enumName, "(v)")
		g.P("	case uint8:")
		g.P("	   *s = ", enumName, "(v)")
		g.P("	case uint:")
		g.P("	   *s = ", enumName, "(v)")
		g.P("	case float64:")
		g.P("	   *s = ", enumName, "(v)")
		g.P("	case float32:")
		g.P("	   *s = ", enumName, "(v)")
		g.P("	case string:")
		g.P("	   parsed, err := strconv.ParseInt(strings.TrimSpace(v), 10, 64)")
		g.P("	   if err != nil {")
		g.P("	      return fmt.Errorf(\"failed to parse ", enumName, " from string: %w\", err)")
		g.P("	   }")
		g.P("	   *s = ", enumName, "(parsed)")
		g.P("	case []byte:")
		g.P("	   parsed, err := strconv.ParseInt(strings.TrimSpace(string(v)), 10, 64)")
		g.P("	   if err != nil {")
		g.P("	      return fmt.Errorf(\"failed to parse ", enumName, " from []byte: %w\", err)")
		g.P("	   }")
		g.P("	   *s = ", enumName, "(parsed)")
	}

	g.P("	default:")
	g.P("	   return fmt.Errorf(\"unsupported type for ", enumName, ": %T (value: %v)\", value, value)")
	g.P("	}")
	g.P("	return nil")
	g.P("}")
	g.P()

	if isStringMode {
		g.P("func (s ", enumName, ") MarshalJSON() ([]byte, error) {")
		g.P("	return json.Marshal(string(s))")
		g.P("}")
		g.P()
		g.P("func (s *", enumName, ") UnmarshalJSON(data []byte) error {")
		g.P("	var str string")
		g.P("	if err := json.Unmarshal(data, &str); err != nil {")
		g.P("	   return err")
		g.P("	}")
		g.P("	*s = ", enumName, "(str)")
		g.P("	return nil")
		g.P("}")
	} else {
		g.P("func (s ", enumName, ") MarshalJSON() ([]byte, error) {")
		g.P("	return json.Marshal(uint8(s))")
		g.P("}")
		g.P()
		g.P("func (s *", enumName, ") UnmarshalJSON(data []byte) error {")
		g.P("	return json.Unmarshal(data, (*uint8)(s))")
		g.P("}")
	}
	g.P()
}

// ---- 组合方法生成 ----

func genComboMethods(g *protogen.GeneratedFile, enum *protogen.Enum) {
	enumName := enum.GoIdent.GoName

	comboDefs := parseComboDefs(enum)
	if len(comboDefs) == 0 {
		return
	}

	comboMap := make(map[string][]string)
	for _, v := range enum.Values {
		for _, combo := range parseComboValues(v) {
			comboMap[combo] = append(comboMap[combo], string(v.Desc.Name()))
		}
	}

	for methodName, values := range comboMap {
		def, ok := comboDefs[methodName]
		if !ok {
			continue
		}

		conditions := []string{}
		for _, value := range values {
			suffix := strings.TrimPrefix(value, camelToSnake(enumName)+"_")
			conditions = append(conditions, "s.Is"+snakeToCamel(suffix)+"()")
		}

		g.P("// ", methodName, " ", def.Description)
		g.P("func (s ", enumName, ") ", methodName, "() bool {")
		g.P("	return ", strings.Join(conditions, " || "))
		g.P("}")
		g.P()
	}
}

func parseComboDefs(enum *protogen.Enum) map[string]ComboDef {
	result := make(map[string]ComboDef)

	extMap := parseEnumExtensionsOptions(enum.Desc.Options().(*descriptorpb.EnumOptions))
	for _, raw := range extMap[comboDefExtensionFileNumber] {
		def := decodeComboDef(raw)
		if def != nil {
			result[def.MethodName] = *def
		}
	}
	return result
}

func decodeComboDef(raw string) *ComboDef {
	buf := []byte(raw)
	var methodName, description string

	for len(buf) > 0 {
		num, wireType, n := protowire.ConsumeTag(buf)
		if n < 0 {
			break
		}
		buf = buf[n:]

		n = protowire.ConsumeFieldValue(num, wireType, buf)
		if n < 0 {
			break
		}
		v := buf[:n]
		buf = buf[n:]

		if wireType == protowire.BytesType {
			if b, nBytes := protowire.ConsumeBytes(v); nBytes >= 0 {
				switch num {
				case 1:
					methodName = string(b)
				case 2:
					description = string(b)
				}
			}
		}
	}

	if methodName == "" {
		return nil
	}
	return &ComboDef{
		MethodName:  methodName,
		Description: description,
	}
}

func parseComboValues(v *protogen.EnumValue) []string {
	extMap := parseEnumValueExtensions(v.Desc.Options().(*descriptorpb.EnumValueOptions))
	combos, ok := extMap[comboExtensionFileNumber]
	if !ok {
		return nil
	}

	var result []string
	for _, raw := range combos {
		for _, name := range strings.Split(raw, ",") {
			name = strings.TrimSpace(name)
			if name != "" {
				result = append(result, name)
			}
		}
	}
	return result
}

// ---- 扩展解析 ----

func parseEnumValueExtensions(options *descriptorpb.EnumValueOptions) map[int32][]string {
	if options == nil {
		return nil
	}
	return extractExtensions(options.ProtoReflect().GetUnknown())
}

func parseEnumExtensionsOptions(options *descriptorpb.EnumOptions) map[int32][]string {
	if options == nil {
		return nil
	}
	return extractExtensions(options.ProtoReflect().GetUnknown())
}

func extractExtensions(unknown []byte) map[int32][]string {
	result := make(map[int32][]string)
	for len(unknown) > 0 {
		num, wireType, n := protowire.ConsumeTag(unknown)
		if n < 0 {
			break
		}
		unknown = unknown[n:]

		n = protowire.ConsumeFieldValue(num, wireType, unknown)
		if n < 0 {
			break
		}
		v := unknown[:n]
		unknown = unknown[n:]

		if wireType == protowire.BytesType {
			if b, nBytes := protowire.ConsumeBytes(v); nBytes >= 0 {
				result[int32(num)] = append(result[int32(num)], string(b))
			}
		}
	}
	return result
}

func getCleanConstantName(enumName, rawValueName string) string {
	prefix := camelToSnake(enumName) + "_"
	if strings.HasPrefix(rawValueName, prefix) {
		suffix := strings.TrimPrefix(rawValueName, prefix)
		return enumName + snakeToCamel(suffix)
	}
	return snakeToCamel(rawValueName)
}

func lowercaseFirst(s string) string {
	if len(s) == 0 {
		return ""
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func snakeToCamel(s string) string {
	parts := strings.Split(strings.ToLower(s), "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func camelToSnake(s string) string {
	var res []rune
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			res = append(res, '_')
		}
		res = append(res, r)
	}
	return strings.ToUpper(string(res))
}
