package main

import (
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/encoding/protowire"
	"google.golang.org/protobuf/types/descriptorpb"
)

const (
	textExtensionFileNumber  = 50001 // 中文描述 (text)
	labelExtensionFileNumber = 50002 // 英文标识 (label)
)

func main() {
	// 使用最稳妥的初始化方式，显式声明支持任何自定义参数，防止被底层过滤
	var targetDir string

	opts := protogen.Options{
		ParamFunc: func(key, value string) error {
			if key == "target_dir" {
				targetDir = value
			}
			return nil
		},
	}

	opts.Run(func(gen *protogen.Plugin) error {
		// 兜底：如果 ParamFunc 在某些特殊工具链下没触发，直接手动暴力切分 Parameter 字符串
		if targetDir == "" && gen.Request.Parameter != nil {
			for _, param := range strings.Split(gen.Request.GetParameter(), ",") {
				parts := strings.SplitN(param, "=", 2)
				if len(parts) == 2 && strings.TrimSpace(parts[0]) == "target_dir" {
					targetDir = strings.TrimSpace(parts[1])
					break
				}
			}
		}

		// 规范化路径分隔符
		if targetDir != "" {
			targetDir = strings.ReplaceAll(targetDir, "\\", "/")
			if !strings.HasSuffix(targetDir, "/") {
				targetDir += "/"
			}
		}

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}

			// 提取文件相对路径并做前缀过滤
			filePath := strings.ReplaceAll(f.Desc.Path(), "\\", "/")
			if targetDir != "" && !strings.HasPrefix(filePath, targetDir) {
				continue // 路径不匹配，直接静默跳过
			}

			generateFile(gen, f)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	if len(file.Enums) == 0 {
		return
	}

	filename := file.GeneratedFilenamePrefix + ".pb.enum.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)

	g.P("// Code generated by protoc-gen-go-enum. DO NOT EDIT.")
	g.P("// source: ", file.Desc.Path())
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	// 1. 动态分析该文件中所有的枚举，看是否存在至少一个 int32 模式的枚举
	hasInt32Mode := false

	type resolvedEnum struct {
		enum         *protogen.Enum
		isStringMode bool
	}
	var list []resolvedEnum

	for _, enum := range file.Enums {
		isStringMode := false
		for _, v := range enum.Values {
			extMap := parseUnknownExtensions(v.Desc.Options().(*descriptorpb.EnumValueOptions))
			if extMap[labelExtensionFileNumber] != "" {
				isStringMode = true
				break
			}
		}
		if !isStringMode {
			hasInt32Mode = true // 存在没有 label 的枚举，后续需要使用 strconv
		}
		list = append(list, resolvedEnum{enum: enum, isStringMode: isStringMode})
	}

	// 2. 根据场景按需生成 import 块
	g.P("import (")
	g.P(`	"database/sql/driver"`)
	g.P(`	"encoding/json"`)
	g.P(`	"fmt"`)
	if hasInt32Mode {
		g.P(`	"strconv"`) // 只有存在 int32 模式枚举时才引入，彻底解决未使用报错
	}
	g.P(")")
	g.P()

	// 3. 开始迭代生成每个枚举的方法
	for _, item := range list {
		genEnumMethods(g, item.enum, item.isStringMode)
	}
}

func genEnumMethods(g *protogen.GeneratedFile, enum *protogen.Enum, isStringMode bool) {
	enumName := enum.GoIdent.GoName
	textMapName := lowercaseFirst(enumName) + "TextMap"

	// 预解析当前枚举项的属性关系
	type enumOpts struct {
		text  string
		label string
	}
	optsResolved := make(map[string]enumOpts)

	for _, v := range enum.Values {
		nameStr := string(v.Desc.Name())
		extMap := parseUnknownExtensions(v.Desc.Options().(*descriptorpb.EnumValueOptions))

		lVal := extMap[labelExtensionFileNumber]
		hasL := lVal != ""
		if !hasL {
			lVal = nameStr
		}

		tVal := extMap[textExtensionFileNumber]
		if tVal == "" {
			if hasL {
				tVal = extMap[labelExtensionFileNumber]
			} else {
				tVal = nameStr
			}
		}

		optsResolved[nameStr] = enumOpts{text: tVal, label: lVal}
	}

	// 根据模式动态生成基础类型
	if isStringMode {
		g.P("type ", enumName, " string")
	} else {
		g.P("type ", enumName, " int32")
	}
	g.P()

	// 动态生成强类型常量块
	g.P("const (")
	for i, v := range enum.Values {
		nameStr := string(v.Desc.Name())
		cleanConstantName := getCleanConstantName(enumName, nameStr)

		if isStringMode {
			g.P("	", cleanConstantName, " ", enumName, ` = "`, optsResolved[nameStr].label, `"`)
		} else {
			if i == 0 {
				g.P("	", cleanConstantName, " ", enumName, " = iota")
			} else {
				g.P("	", cleanConstantName)
			}
		}
	}
	g.P(")")
	g.P()

	// 生成 Text 映射 Map
	g.P("var ", textMapName, " = map[", enumName, "]string{")
	for _, v := range enum.Values {
		nameStr := string(v.Desc.Name())
		cleanConstantName := getCleanConstantName(enumName, nameStr)
		g.P("	", cleanConstantName, `: "`, optsResolved[nameStr].text, `",`)
	}
	g.P("}")
	g.P()

	// GetValue() 方法自适应返回
	if isStringMode {
		g.P("func (s ", enumName, ") GetValue() string {")
		g.P("	return string(s)")
		g.P("}")
	} else {
		g.P("func (s ", enumName, ") GetValue() int32 {")
		g.P("	return int32(s)")
		g.P("}")
	}
	g.P()

	// GetText() 方法
	g.P("func (s ", enumName, ") GetText() string {")
	g.P("	tex, ok := ", textMapName, "[s]")
	g.P("	if !ok {")
	g.P("	   return \"\"")
	g.P("	}")
	g.P("	return tex")
	g.P("}")
	g.P()

	// IsXXX 判断谓词方法
	for _, v := range enum.Values {
		nameStr := string(v.Desc.Name())
		suffix := strings.TrimPrefix(nameStr, camelToSnake(enumName)+"_")
		methodName := "Is" + snakeToCamel(suffix)
		cleanConstantName := getCleanConstantName(enumName, nameStr)

		g.P("func (s ", enumName, ") ", methodName, "() bool {")
		g.P("	return s == ", cleanConstantName)
		g.P("}")
		g.P()
	}

	// 挂载 GORM 的 Value() 方法
	g.P("func (s ", enumName, ") Value() (driver.Value, error) {")
	if isStringMode {
		g.P("	return string(s), nil")
	} else {
		g.P("	return int64(s), nil")
	}
	g.P("}")
	g.P()

	// 挂载 GORM 的 Scan() 方法
	g.P("func (s *", enumName, ") Scan(value interface{}) error {")
	g.P("	if value == nil {")
	if isStringMode {
		firstValueName := string(enum.Values[0].Desc.Name())
		g.P("	   *s = \"", optsResolved[firstValueName].label, "\"")
	} else {
		g.P("	   *s = 0")
	}
	g.P("	   return nil")
	g.P("	}")
	g.P()
	g.P("	switch v := value.(type) {")

	if isStringMode {
		g.P("	case string:")
		g.P("	   *s = ", enumName, "(v)")
		g.P("	case []byte:")
		g.P("	   *s = ", enumName, "(string(v))")
	} else {
		g.P("	case int64:")
		g.P("	   *s = ", enumName, "(v)")
		g.P("	case int32:")
		g.P("	   *s = ", enumName, "(v)")
		g.P("	case int:")
		g.P("	   *s = ", enumName, "(v)")
		g.P("	case uint64:")
		g.P("	   *s = ", enumName, "(v)")
		g.P("	case []byte:")
		g.P("	   parsed, err := strconv.ParseInt(string(v), 10, 64)")
		g.P("	   if err != nil {")
		g.P("	      return fmt.Errorf(\"failed to parse ", enumName, " from []byte: %w\", err)")
		g.P("	   }")
		g.P("	   *s = ", enumName, "(parsed)")
		g.P("	case string:")
		g.P("	   parsed, err := strconv.ParseInt(v, 10, 64)")
		g.P("	   if err != nil {")
		g.P("	      return fmt.Errorf(\"failed to parse ", enumName, " from string: %w\", err)")
		g.P("	   }")
		g.P("	   *s = ", enumName, "(parsed)")
	}

	g.P("	default:")
	g.P("	   return fmt.Errorf(\"unsupported type for ", enumName, ": %T (value: %v)\", value, value)")
	g.P("	}")
	g.P("	return nil")
	g.P("}")
	g.P()

	// 挂载 MarshalJSON() 与 UnmarshalJSON()
	if isStringMode {
		g.P("func (s ", enumName, ") MarshalJSON() ([]byte, error) {")
		g.P("	return json.Marshal(string(s))")
		g.P("}")
		g.P()
		g.P("func (s *", enumName, ") UnmarshalJSON(data []byte) error {")
		g.P("	var str string")
		g.P("	if err := json.Unmarshal(data, &str); err != nil {")
		g.P("	   return err")
		g.P("	}")
		g.P("	*s = ", enumName, "(str)")
		g.P("	return nil")
		g.P("}")
	} else {
		g.P("func (s ", enumName, ") MarshalJSON() ([]byte, error) {")
		g.P("	return json.Marshal(int32(s))")
		g.P("}")
		g.P()
		g.P("func (s *", enumName, ") UnmarshalJSON(data []byte) error {")
		g.P("	return json.Unmarshal(data, (*int32)(s))")
		g.P("}")
	}
	g.P()
}

func parseUnknownExtensions(options *descriptorpb.EnumValueOptions) map[int32]string {
	res := make(map[int32]map[string]struct{})
	finalMap := make(map[int32]string)
	if options == nil {
		return finalMap
	}

	unknown := options.ProtoReflect().GetUnknown()
	for len(unknown) > 0 {
		num, wireType, n := protowire.ConsumeTag(unknown)
		if n < 0 {
			break
		}
		unknown = unknown[n:]

		n = protowire.ConsumeFieldValue(num, wireType, unknown)
		if n < 0 {
			break
		}
		v := unknown[:n]
		unknown = unknown[n:]

		if wireType == protowire.BytesType {
			if b, nBytes := protowire.ConsumeBytes(v); nBytes >= 0 {
				strVal := string(b)
				if _, ok := res[int32(num)]; !ok {
					res[int32(num)] = make(map[string]struct{})
				}
				res[int32(num)][strVal] = struct{}{}
			}
		}
	}

	for tag, valMap := range res {
		var parts []string
		for k := range valMap {
			parts = append(parts, k)
		}
		finalMap[tag] = strings.Join(parts, ",")
	}
	return finalMap
}

func getCleanConstantName(enumName, rawValueName string) string {
	prefix := camelToSnake(enumName) + "_"
	if strings.HasPrefix(rawValueName, prefix) {
		suffix := strings.TrimPrefix(rawValueName, prefix)
		return enumName + snakeToCamel(suffix)
	}
	return snakeToCamel(rawValueName)
}

func lowercaseFirst(s string) string {
	if len(s) == 0 {
		return ""
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func snakeToCamel(s string) string {
	parts := strings.Split(strings.ToLower(s), "_")
	for i, part := range parts {
		if len(part) > 0 {
			parts[i] = strings.ToUpper(part[:1]) + part[1:]
		}
	}
	return strings.Join(parts, "")
}

func camelToSnake(s string) string {
	var res []rune
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			res = append(res, '_')
		}
		res = append(res, r)
	}
	return strings.ToUpper(string(res))
}
